[www]
; Havuz adı
; 'www' varsayılan havuz adıdır
; Birden fazla havuz gerektiğinde farklı isimler kullanılabilir.

; Kullanıcı ve grup
user = www-data
group = www-data

; PHP-FPM'nin dinleyeceği adres ve port
listen = wordpress:9000

; Süreç yönetim modu
pm = dynamic

;  Aynı anda çalışabilecek maksimum işlem sayısı
pm.max_children = 50

; Başlangıçta başlatılacak işlem sayısı
pm.start_servers = 5

; Her zaman hazır tutulacak minimum işlem sayısı
pm.min_spare_servers = 2

; Her zaman hazır tutulacak maksimum işlem sayısı
pm.max_spare_servers = 10
